### ISSUE TITLE
Error 'NoneType' object has no attribute 'write'

### ISSUE THREAD

**Issue by RameshKumarGogoi** [FreeLanguageTools/vocabsieve#15]
While trying to add note I get this error " 'NoneType' object has no attribute 'write' "
My anki settings :
![image](https://user-images.githubusercontent.com/61318157/167249282-7e85e3a5-e005-4029-868b-97862dae5786.png)

**Comment by 1over137** [comment]
What OS? Latest version? 
Also, how did the error appear: on the status bar, or on a warning window, or on the standard output?

**Comment by expacc007** [comment]
Windows 11
![image](https://user-images.githubusercontent.com/61318157/167264635-012533b6-fc4b-49e6-98e2-c5d9f79121a9.png)
The sentence was " the __standard__ output " it looks different because it clipboard autocopy while taking screenshot.
Anki is running.

**Comment by 1over137** [comment]
There might have been a bug in the earlier implementation which suppresses standard output when making a note.
Can you try using this latest build? https://ci.appveyor.com/api/buildjobs/w6soviu9n0gukkw8/artifacts/cx_freeze%2Fdist%2FVocabSieve-0.8.0-win64.msi

**Comment by expacc007** [comment]
Same bug with v 0.8.0. This might be a windows 11 bug.

**Comment by 1over137** [comment]
That warning window appears because there is an underlying error which is masked by the exception catching mechanism. I removed the exception catching code temporarily. Try installing this version:
https://ci.appveyor.com/api/buildjobs/b0a0yy0iuqvnylb5/artifacts/cx_freeze%2Fdist%2FVocabSieve-0.8.0-win64.msi

This time, it should give a longer error with more details, though it might crash.

**Comment by expacc007** [comment]
It crashed on anki Version ⁨2.1.50 however it worked on anki Version ⁨2.1.35. I tried immersive, it is working.

**Comment by 1over137** [comment]
I was using 2.1.49 for testing, since 2.1.51 is not considered stable yet, and Anki has a tendency to break addons on each release in mysterious ways.
However, I installed 2.1.51 on my win10 vm, and it seems to work pretty normally.

**Comment by 1over137** [comment]
Does this still happen? From what I tested with win10, I have not seen anything like this.
